index.search.slowlog.threshold:
  query:
    warn: 3s
    info: 1s
    debug: 500ms
    trace: 100ms

path.logs: /var/log/elasticsearch

script.groovy.sandbox.enabled: true
http.cors.enabled: true
threadpool:
  search:
    type: cached
